# API cluster definition
upstream api_cluster {
    # Shared memory zone to track runtime DNS resolution across worker processes
    zone api_cluster_zone 64k;

    # 'resolve' tells Nginx to skip boot validation and dynamically look up IPs
    server api:8000 max_fails=3 fail_timeout=10s resolve;
    
    # Used seamlessly while the above containers are down/booting
    server 127.0.0.1:9999 backup;
    
    # Resolver
    resolver 127.0.0.11 valid=10s;

    keepalive 32;
    least_conn;
}
